// examples/vue-app/src/components/AnalyticsTracker.vue
<script setup lang="ts">
import { ref, watchEffect } from "vue";
import { useConsent, useConsentService } from "@solvenza/cookies-compliance/vue";

const hasAnalytics = useConsent("analytics");
const hasGa4 = useConsentService("ga4");
const eventLog = ref<string[]>([]);

watchEffect(() => {
  if (hasAnalytics.value) {
    eventLog.value.push(`[${new Date().toLocaleTimeString()}] ✅ Analítica activada: Inicializando GA4`);
  } else {
    eventLog.value.push(`[${new Date().toLocaleTimeString()}] ⛔ Analítica bloqueada: Tracking inactivo`);
  }
});

function simulateEvent() {
  if (hasGa4.value) {
    eventLog.value.push(`[${new Date().toLocaleTimeString()}] 📊 Evento enviado a GA4: 'user_action_click'`);
  } else {
    eventLog.value.push(`[${new Date().toLocaleTimeString()}] 🚫 Evento descartado (Consentimiento no otorgado)`);
  }
}
</script>

<template>
  <div style="background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
    <h3 style="margin-top: 0; color: #1e293b; font-size: 1.15rem; display: flex; align-items: center; gap: 0.5rem;">
      <span>📈</span> Tracker Reactivo con Composables Vue 3 (`useConsent`)
    </h3>
    <p style="color: #64748b; font-size: 0.9rem; margin-bottom: 1rem;">
      Estado reactivo de la categoría:
      <span
        :style="{
          display: 'inline-block',
          padding: '0.2rem 0.6rem',
          borderRadius: '9999px',
          fontWeight: '600',
          fontSize: '0.82rem',
          marginLeft: '0.4rem',
          background: hasAnalytics ? '#dcfce7' : '#fee2e2',
          color: hasAnalytics ? '#166534' : '#991b1b'
        }"
      >
        {{ hasAnalytics ? 'Autorizado (analytics = true)' : 'Bloqueado (analytics = false)' }}
      </span>
    </p>

    <button
      @click="simulateEvent"
      style="
        background: #0f172a;
        color: #ffffff;
        border: none;
        padding: 0.55rem 1.1rem;
        border-radius: 6px;
        font-weight: 600;
        font-size: 0.85rem;
        cursor: pointer;
        margin-bottom: 1rem;
      "
    >
      Simular Evento de Analítica
    </button>

    <div style="background: #0f172a; color: #e2e8f0; font-family: monospace; font-size: 0.82rem; padding: 0.85rem; border-radius: 8px; max-height: 120px; overflow-y: auto;">
      <div v-for="(log, idx) in eventLog" :key="idx">{{ log }}</div>
    </div>
  </div>
</template>

// examples/react-app/src/components/AnalyticsTracker.tsx
import { useEffect } from "react";
import { useConsent } from "@solvenza/cookies-compliance/react";

export function AnalyticsTracker() {
  const isAnalyticsAllowed = useConsent("analytics");

  useEffect(() => {
    if (isAnalyticsAllowed) {
      console.log("[Solvenza React] Analytics telemetry initialized.");
    }
  }, [isAnalyticsAllowed]);

  return (
    <div
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "0.5rem",
        padding: "0.4rem 0.9rem",
        borderRadius: "9999px",
        background: isAnalyticsAllowed ? "rgba(16, 185, 129, 0.1)" : "rgba(239, 68, 68, 0.1)",
        border: `1px solid ${isAnalyticsAllowed ? "rgba(16, 185, 129, 0.2)" : "rgba(239, 68, 68, 0.2)"}`,
        color: isAnalyticsAllowed ? "#059669" : "#dc2626",
        fontSize: "0.82rem",
        fontWeight: 600,
        letterSpacing: "0.01em",
      }}
    >
      <span
        style={{
          width: "7px",
          height: "7px",
          borderRadius: "50%",
          background: isAnalyticsAllowed ? "#10b981" : "#ef4444",
          boxShadow: isAnalyticsAllowed ? "0 0 8px #10b981" : "none",
        }}
      />
      Analítica: {isAnalyticsAllowed ? "Activa" : "Bloqueada"}
    </div>
  );
}
