// examples/react-app/src/App.tsx
import { useEffect, useState } from "react";
import { Consent, ConsentConfigBuilder } from "@solvenza/cookies-compliance";
import { useSyncConsentLocale } from "@solvenza/cookies-compliance/react";
import { AnalyticsTracker } from "./components/AnalyticsTracker";
import { YouTubeWidget } from "./components/YouTubeWidget";
import { CookiePolicyPage } from "./pages/CookiePolicyPage";

export function App() {
  const [initialized, setInitialized] = useState(false);
  const [activeTab, setActiveTab] = useState<"demo" | "policy">("demo");
  const [parentAppLocale, setParentAppLocale] = useState("es");

  // Zero-boilerplate hook: when the parent React app changes language, the cookie engine syncs automatically
  useSyncConsentLocale(parentAppLocale);

  useEffect(() => {
    const config = new ConsentConfigBuilder("2026-08-23")
      .setLegalEntity({
        name: "Solvenza Inteligencia Artificial S.L.",
        tradeName: "Solvenza",
        taxId: "B-12345678",
        address: "Paseo de la Castellana 100, 28046 Madrid, España",
        email: "privacidad@solvenza.es",
        phone: "+34 910 000 000",
        registryData: "Registro Mercantil de Madrid, Tomo 1234, Folio 56, Sección 8",
        dpoEmail: "dpo@solvenza.es",
      })
      .setLegalNotice({
        applicableLaw: "Legislación española (LSSI-CE, LOPDGDD) y Reglamento General de Protección de Datos (RGPD UE 2016/679)",
        jurisdiction: "Juzgados y Tribunales de Madrid",
        lastUpdated: "2026-09-30",
      })
      .setPolicyUrls("/politica-privacidad", "/politica-cookies")
      .setLocale("es", true, ["es", "en", "ca", "eu", "gl"])
      .setFloatingBadge({
        enabled: true,
        position: "bottom-left",
        icon: "cookie",
        label: "Cookies",
      })
      .addTranslation("en", {
        policy: {
          privacyUrl: "/en/privacy-policy",
          cookiesUrl: "/en/cookie-policy",
        },
        ui: {
          banner: {
            title: "Your privacy, your choice",
            accept: "Accept all",
          },
          floatingBadge: {
            label: "Cookies",
            tooltip: "Cookie preferences & revocation",
          },
        },
        categories: {
          analytics: {
            label: "Usage Analytics",
            description: "Allows aggregated usage measurement to improve the app.",
          },
          marketing: {
            label: "Marketing & Video",
            description: "Allows embedded video playback and personalization.",
          },
        },
      })
      .addCategory("analytics", {
        required: false,
        label: "Analítica de uso",
        description: "Permite medir de forma agregada cómo se utiliza la aplicación.",
      })
      .addCategory("marketing", {
        required: false,
        label: "Marketing y Vídeo",
        description: "Permite la reproducción de vídeos incrustados y personalización.",
      })
      .addService("ga4", {
        category: "analytics",
        label: "Google Analytics 4",
        provider: "Google",
      })
      .addService("youtube", {
        category: "marketing",
        label: "YouTube Embed",
        provider: "Google",
      })
      .build();

    void Consent.init(config).then(() => {
      setInitialized(true);
    });
  }, []);

  if (!initialized) return null;

  return (
    <div style={{ minHeight: "100vh", background: "#f8fafc", fontFamily: "system-ui, -apple-system, sans-serif", color: "#0f172a" }}>
      {/* Sleek Top Navigation */}
      <header
        style={{
          borderBottom: "1px solid #e2e8f0",
          background: "#ffffff",
          padding: "1rem 2rem",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "0.8rem" }}>
          <div
            style={{
              width: "32px",
              height: "32px",
              borderRadius: "8px",
              background: "linear-gradient(135deg, #2563eb, #7c3aed)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#ffffff",
              fontWeight: 700,
              fontSize: "0.9rem",
            }}
          >
            S
          </div>
          <span style={{ fontWeight: 700, fontSize: "1.05rem", letterSpacing: "-0.01em" }}>Solvenza Cookies Compliance</span>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
          {/* Host App Language Switcher (automatically synced to cookie engine via useSyncConsentLocale) */}
          <div style={{ display: "flex", alignItems: "center", gap: "0.25rem", background: "#f1f5f9", borderRadius: "8px", padding: "3px 6px" }}>
            <span style={{ fontSize: "0.75rem", fontWeight: 700, color: "#64748b", paddingRight: "4px" }}>🌐 i18n:</span>
            {(["es", "en", "ca", "eu", "gl"] as const).map((lang) => (
              <button
                key={lang}
                type="button"
                onClick={() => setParentAppLocale(lang)}
                style={{
                  border: "none",
                  background: parentAppLocale === lang ? "#0f172a" : "transparent",
                  color: parentAppLocale === lang ? "#ffffff" : "#475569",
                  padding: "0.25rem 0.55rem",
                  borderRadius: "6px",
                  fontWeight: 700,
                  fontSize: "0.75rem",
                  cursor: "pointer",
                  transition: "all 0.15s ease",
                }}
              >
                {lang.toUpperCase()}
              </button>
            ))}
          </div>

          <nav style={{ display: "flex", gap: "0.4rem" }}>
            <button
              onClick={() => setActiveTab("demo")}
              style={{
                border: "none",
                background: activeTab === "demo" ? "#f1f5f9" : "transparent",
                color: activeTab === "demo" ? "#0f172a" : "#64748b",
                padding: "0.5rem 0.9rem",
                borderRadius: "8px",
                fontWeight: 600,
                fontSize: "0.88rem",
                cursor: "pointer",
              }}
            >
              {parentAppLocale === "en" ? "Demo" : "Demostración"}
            </button>
            <button
              onClick={() => setActiveTab("policy")}
              style={{
                border: "none",
                background: activeTab === "policy" ? "#f1f5f9" : "transparent",
                color: activeTab === "policy" ? "#0f172a" : "#64748b",
                padding: "0.5rem 0.9rem",
                borderRadius: "8px",
                fontWeight: 600,
                fontSize: "0.88rem",
                cursor: "pointer",
              }}
            >
              {parentAppLocale === "en" ? "Cookie Policy" : "Política de Cookies"}
            </button>
          </nav>
        </div>
      </header>

      {/* Main Content Area */}
      <main style={{ maxWidth: "760px", margin: "2.5rem auto", padding: "0 1.5rem" }}>
        {activeTab === "demo" ? (
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem" }}>
              <div>
                <h1 style={{ fontSize: "1.5rem", fontWeight: 700, margin: 0, letterSpacing: "-0.02em" }}>
                  Integración React 18+
                </h1>
                <p style={{ margin: "0.2rem 0 0 0", color: "#64748b", fontSize: "0.92rem" }}>
                  Comportamiento reactivo out-of-the-box con TypeScript
                </p>
              </div>
              <AnalyticsTracker />
            </div>

            <YouTubeWidget />

            {/* Minimal Action Bar */}
            <div
              style={{
                marginTop: "2rem",
                display: "flex",
                gap: "0.8rem",
                alignItems: "center",
                justifyContent: "flex-end",
              }}
            >
              <button
                onClick={() => Consent.openPreferences()}
                style={{
                  padding: "0.65rem 1.3rem",
                  borderRadius: "10px",
                  border: "none",
                  background: "#0f172a",
                  color: "#ffffff",
                  fontWeight: 600,
                  fontSize: "0.88rem",
                  cursor: "pointer",
                  boxShadow: "0 4px 12px rgba(15, 23, 42, 0.15)",
                }}
              >
                Ajustes de Privacidad
              </button>
              <button
                onClick={() => Consent.withdraw()}
                style={{
                  padding: "0.65rem 1.1rem",
                  borderRadius: "10px",
                  border: "1px solid #cbd5e1",
                  background: "#ffffff",
                  color: "#ef4444",
                  fontWeight: 600,
                  fontSize: "0.88rem",
                  cursor: "pointer",
                }}
              >
                Revocar
              </button>
            </div>
          </div>
        ) : (
          <CookiePolicyPage />
        )}
      </main>

      {/* Sleek Footer */}
      <footer style={{ marginTop: "4rem", textAlign: "center", padding: "2rem 0", color: "#94a3b8", fontSize: "0.82rem" }}>
        <span>Solvenza Cookies Compliance &bull; LSSI art. 22.2 &amp; AEPD 2024 &bull; </span>
        <button
          type="button"
          data-consent-open
          style={{ border: "none", background: "none", color: "#64748b", cursor: "pointer", textDecoration: "underline", fontSize: "0.82rem" }}
        >
          Configurar preferencias
        </button>
      </footer>
    </div>
  );
}

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { Consent, ConsentConfigBuilder } from "@solvenza/cookies-compliance";
import { useSyncConsentLocale } from "@solvenza/cookies-compliance/vue";
import AnalyticsTracker from "./components/AnalyticsTracker.vue";
import YouTubeWidget from "./components/YouTubeWidget.vue";
import GpcStatus from "./components/GpcStatus.vue";
import CookiePolicyPage from "./components/CookiePolicyPage.vue";

const initialized = ref(false);
const activeTab = ref<"demo" | "policy">("demo");
const parentAppLocale = ref("es");

// Zero-boilerplate hook: when the Vue app switches language, the consent engine updates automatically
useSyncConsentLocale(parentAppLocale);

onMounted(async () => {
  const config = new ConsentConfigBuilder("2026-08-23")
    .setLegalEntity({
      name: "Solvenza Inteligencia Artificial S.L.",
      tradeName: "Solvenza",
      taxId: "B-12345678",
      address: "Paseo de la Castellana 100, 28046 Madrid, España",
      email: "privacidad@solvenza.es",
      phone: "+34 910 000 000",
      registryData: "Registro Mercantil de Madrid, Tomo 1234, Folio 56, Sección 8, Hoja M-12345",
      dpoEmail: "dpo@solvenza.es",
    })
    .setLegalNotice({
      applicableLaw: "Legislación española (LSSI-CE, LOPDGDD) y Reglamento General de Protección de Datos (RGPD UE 2016/679)",
      jurisdiction: "Juzgados y Tribunales de Madrid",
      lastUpdated: "2026-09-30",
    })
    .setPolicyUrls("/politica-privacidad", "/politica-cookies")
    .setLocale("es", true, ["es", "en", "ca"])
    .setFloatingBadge({
      enabled: true,
      position: "bottom-left",
      icon: "cookie",
      label: "Cookies"
    })
    .addCategory("analytics", {
      required: false,
      label: "Analítica de uso",
      description: "Permite medir de forma agregada cómo se utiliza la aplicación.",
      storageKeys: ["_ga*", "mp_*"]
    })
    .addCategory("marketing", {
      required: false,
      label: "Marketing y Vídeo",
      description: "Permite la reproducción de vídeos incrustados y personalización.",
      storageKeys: ["yt-*", "vuid"]
    })
    .addService("ga4", {
      category: "analytics",
      label: "Google Analytics 4",
      provider: "Google"
    })
    .addService("youtube", {
      category: "marketing",
      label: "YouTube Embed",
      provider: "Google"
    })
    .build();

  await Consent.init(config);
  initialized.value = true;
});

function setLocale(lang: string) {
  parentAppLocale.value = lang;
}

function openPreferences() {
  Consent.openPreferences();
}

function withdrawConsent() {
  Consent.withdraw();
}

function acceptAll() {
  Consent.acceptAll();
}

function rejectAll() {
  Consent.rejectAll();
}
</script>

<template>
  <div v-if="initialized" style="min-height: 100vh; background: #f8fafc; font-family: system-ui, -apple-system, sans-serif; color: #0f172a;">
    <!-- Top Navigation -->
    <header
      style="
        border-bottom: 1px solid #e2e8f0;
        background: #ffffff;
        padding: 1rem 2rem;
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-wrap: wrap;
        gap: 1rem;
      "
    >
      <div style="display: flex; align-items: center; gap: 0.8rem;">
        <div
          style="
            width: 34px;
            height: 34px;
            border-radius: 8px;
            background: linear-gradient(135deg, #42b883, #35495e);
            display: flex;
            align-items: center;
            justify-content: center;
            color: #ffffff;
            font-weight: 700;
            font-size: 1.1rem;
          "
        >
          V
        </div>
        <div>
          <h1 style="margin: 0; font-size: 1.15rem; font-weight: 700;">Vue 3 & Nuxt 3 — Cookies Compliance</h1>
          <p style="margin: 0; font-size: 0.78rem; color: #64748b;">@solvenza/cookies-compliance/vue</p>
        </div>
      </div>

      <!-- Center Tabs & Language Selector -->
      <div style="display: flex; align-items: center; gap: 1rem; flex-wrap: wrap;">
        <div style="display: flex; gap: 0.3rem; background: #f1f5f9; padding: 0.25rem; border-radius: 8px;">
          <button
            @click="activeTab = 'demo'"
            :style="{
              padding: '0.4rem 0.8rem',
              borderRadius: '6px',
              fontWeight: '600',
              fontSize: '0.85rem',
              cursor: 'pointer',
              border: 'none',
              background: activeTab === 'demo' ? '#ffffff' : 'transparent',
              color: activeTab === 'demo' ? '#0f172a' : '#64748b',
              boxShadow: activeTab === 'demo' ? '0 1px 2px rgba(0,0,0,0.05)' : 'none'
            }"
          >
            Demo de Componentes
          </button>
          <button
            @click="activeTab = 'policy'"
            :style="{
              padding: '0.4rem 0.8rem',
              borderRadius: '6px',
              fontWeight: '600',
              fontSize: '0.85rem',
              cursor: 'pointer',
              border: 'none',
              background: activeTab === 'policy' ? '#ffffff' : 'transparent',
              color: activeTab === 'policy' ? '#0f172a' : '#64748b',
              boxShadow: activeTab === 'policy' ? '0 1px 2px rgba(0,0,0,0.05)' : 'none'
            }"
          >
            Declaración de Cookies
          </button>
        </div>

        <div style="display: flex; align-items: center; gap: 0.4rem; background: #f1f5f9; padding: 0.25rem; border-radius: 8px;">
          <button
            v-for="lang in ['es', 'en', 'ca']"
            :key="lang"
            @click="setLocale(lang)"
            :style="{
              padding: '0.35rem 0.7rem',
              borderRadius: '6px',
              fontWeight: '700',
              fontSize: '0.8rem',
              cursor: 'pointer',
              border: 'none',
              background: parentAppLocale === lang ? '#0f172a' : 'transparent',
              color: parentAppLocale === lang ? '#ffffff' : '#475569'
            }"
          >
            {{ lang.toUpperCase() }}
          </button>
        </div>
      </div>
    </header>

    <!-- Main Container -->
    <main style="max-width: 900px; margin: 2rem auto; padding: 0 1.5rem;">
      <template v-if="activeTab === 'demo'">
        <!-- Hero Card -->
        <div
          style="
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 16px;
            padding: 1.75rem;
            margin-bottom: 2rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
          "
        >
          <h2 style="margin-top: 0; color: #0f172a; font-size: 1.35rem;">Integración Reactiva en Vue 3 y Nuxt 3</h2>
          <p style="color: #475569; line-height: 1.6; margin-bottom: 1.25rem;">
            Este ejemplo demuestra la utilización de los composables reactivos oficiales (<code>useConsent</code>, <code>useConsentService</code>, <code>useGpc</code>, <code>useSyncConsentLocale</code>) y el componente declarativo <code>&lt;ConsentGate&gt;</code> en aplicaciones Vue 3 y Nuxt 3.
          </p>

          <!-- Action Buttons -->
          <div style="display: flex; flex-wrap: wrap; gap: 0.6rem;">
            <button
              @click="openPreferences"
              style="
                background: #0f172a;
                color: #ffffff;
                border: none;
                padding: 0.6rem 1.2rem;
                border-radius: 8px;
                font-weight: 600;
                font-size: 0.88rem;
                cursor: pointer;
              "
            >
              ⚙️ Abrir Preferencias (2ª Capa)
            </button>
            <button
              @click="acceptAll"
              style="
                background: #16a34a;
                color: #ffffff;
                border: none;
                padding: 0.6rem 1.2rem;
                border-radius: 8px;
                font-weight: 600;
                font-size: 0.88rem;
                cursor: pointer;
              "
            >
              ✅ Aceptar Todas
            </button>
            <button
              @click="rejectAll"
              style="
                background: #dc2626;
                color: #ffffff;
                border: none;
                padding: 0.6rem 1.2rem;
                border-radius: 8px;
                font-weight: 600;
                font-size: 0.88rem;
                cursor: pointer;
              "
            >
              ❌ Rechazar Opcionales
            </button>
            <button
              @click="withdrawConsent"
              style="
                background: #ffffff;
                color: #dc2626;
                border: 1px solid #fca5a5;
                padding: 0.6rem 1.2rem;
                border-radius: 8px;
                font-weight: 600;
                font-size: 0.88rem;
                cursor: pointer;
              "
            >
              🔄 Revocar / Reiniciar
            </button>
          </div>
        </div>

        <!-- Feature Demos -->
        <YouTubeWidget />
        <AnalyticsTracker />
        <GpcStatus />
      </template>

      <template v-else>
        <CookiePolicyPage />
      </template>
    </main>

    <!-- Footer -->
    <footer style="text-align: center; padding: 2rem; color: #64748b; font-size: 0.85rem; border-top: 1px solid #e2e8f0;">
      Solvenza Cookies Compliance — Adaptado a LSSI art. 22.2, AEPD mayo 2024 y RGPD.
    </footer>
  </div>
</template>
